# permissions for end users to edit users.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: headscale-operator
    app.kubernetes.io/managed-by: kustomize
  name: user-editor-role
rules:
- apiGroups:
  - headscale.azaurus.dev
  resources:
  - users
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - headscale.azaurus.dev
  resources:
  - users/status
  verbs:
  - get
